### ISSUE TITLE
ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by ndarilek** [ogomez92/launchtype#3]
Not a huge Python user, so maybe this isn't the correct way to launch this, but I'm getting the below error:

```
~\src\launchtype> python src/main.py                        02/27/24 11:01:17 AM
Traceback (most recent call last):                                              
  File "C:\Users\nolan\src\launchtype\src\main.py", line 3, in <module>         
    from managers.ui_manager import UIManager                                   
  File "C:\Users\nolan\src\launchtype\src\managers\ui_manager.py", line 6, in <module>                                                                          
    from services.speech_service import SpeechService                           
  File "C:\Users\nolan\src\launchtype\src\services\speech_service.py", line 1, in <module>                                                                      
    import accessible_output2.outputs.auto                                      
  File "C:\Users\nolan\AppData\Local\Programs\Python\Python312\Lib\site-packages\accessible_output2\__init__.py", line 5, in <module>                           
    from platform_utils import paths                                            
  File "C:\Users\nolan\AppData\Local\Programs\Python\Python312\Lib\site-packages\platform_utils\paths.py", line 20, in <module>                                 
    is_pyinstaller = is_frozen() and getattr(sys, '_MEIPASS', False)            
                     ^^^^^^^^^^^                                                
  File "C:\Users\nolan\AppData\Local\Programs\Python\Python312\Lib\site-packages\platform_utils\paths.py", line 11, in is_frozen                                
    import imp                                                                  
ModuleNotFoundError: No module named 'imp'                                      
 ```

Ran `pip install -r requirements.txt` before running that and it seemed to complete successfully. Is there another step I'm missing?

Thanks.

**Comment by ndarilek** [comment]
Looks like the imp module may be deprecated and not present in python 3.12, which is what I'm running both here and on the work laptop. Also seems to be in a dependency so not directly under your control.

How hard would it be to ship a Windows executable for this so it can presumably be built in CI with an older version of Python?

Thanks.

**Comment by ogomez92** [comment]
Hello.
Try the latest release which I justn posted
https://github.com/ogomez92/launchtype/releases/tag/v3.0.1
