### ISSUE TITLE
KeyError: 'path'

### ISSUE THREAD

**Issue by ndarilek** [ogomez92/launchtype#4]
Getting the following when running in snippets mode, arrowing to a snippet, and attempting to copy it to the clipboard.

Traceback (most recent call last):                                                                                      
  File "C:\Users\nolan\src\launchtype\src\managers\ui_manager.py", line 132, in copyButtonClicked                       
    with CommandEditionDialog(                                                                                          
         ^^^^^^^^^^^^^^^^^^^^^                                                                                          
  File "C:\Users\nolan\src\launchtype\src\ui\command_edition_dialog.py", line 37, in __init__                           
    if not command_to_edit == {} and command_to_edit["path"]:                                                           
                                     ~~~~~~~~~~~~~~~^^^^^^^^                                                            
KeyError: 'path'                                                                                                        

I noticed that I'd given a snippet a wrong filename (typed "gameway" instead of "gateway" in the name) and updated it in the folder, so maybe that's the reason? Maybe a Refresh button would be helpful?

Thanks.

**Comment by ogomez92** [comment]
It should auto refresh every time the program is launched at least. Did it
work now?
